# Generated by Django 2.2.3 on 2019-07-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('creator_name', models.CharField(max_length=75)),
                ('topping_1', models.CharField(choices=[('PEP', 'Pepperoni'), ('MUS', 'Mushrooms'), ('ONI', 'Onions'), ('SAU', 'Sausage'), ('BAC', 'Bacon'), ('ECH', 'Extra Cheese'), ('BOL', 'Black Olives'), ('GPP', 'Green Peppers'), ('CHO', 'Chocolate')], max_length=5)),
                ('topping_3', models.CharField(choices=[('PEP', 'Pepperoni'), ('MUS', 'Mushrooms'), ('ONI', 'Onions'), ('SAU', 'Sausage'), ('BAC', 'Bacon'), ('ECH', 'Extra Cheese'), ('BOL', 'Black Olives'), ('GPP', 'Green Peppers'), ('CHO', 'Chocolate')], max_length=5)),
                ('topping_2', models.CharField(choices=[('PEP', 'Pepperoni'), ('MUS', 'Mushrooms'), ('ONI', 'Onions'), ('SAU', 'Sausage'), ('BAC', 'Bacon'), ('ECH', 'Extra Cheese'), ('BOL', 'Black Olives'), ('GPP', 'Green Peppers'), ('CHO', 'Chocolate')], max_length=5)),
                ('size', models.IntegerField()),
                ('cooking', models.CharField(choices=[('RW', 'Raw'), ('MD', 'Medium'), ('SK', 'Smoked')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
            ],
        ),
    ]
